swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "0.1.0"
  title: Swagger REST env_data
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: "users.read"
      tags:
        - "Users"
      summary: "The users data structure supported by the server application"
      description: "Read the list of users"
      responses:
        200:
          description: "Successful read user list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "string"
                name:
                  type: "string"
